version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8000:8080
    environment:
      - API_URL=http://localhost:8000/api/game_base.yml
    volumes:
      - ./docs/apis:/usr/share/nginx/html/api
