version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8888:8080
    environment:
      - API_URL=http://localhost:8000/api/game_base.yml
    volumes:
      - ./docs/apis:/usr/share/nginx/html/api
volumes:
  db_data:
